// Generated by CoffeeScript 1.7.1
(function() {
  var beer_lover, drinkbeer, fridge, hello, i, item, items, _i, _j, _k, _len, _len1;

  items = ['beer1', 'beer2', 'beer3', 'beer4'];

  fridge = 'full of beer';

  if (fridge === 'full of beer') {
    beer_lover = true;
  }

  if (fridge === 'full of beer' && items.length > 0) {
    beer_lover = true;
  }

  while (items.length > 0) {
    drinkBeer();
  }

  for (_i = 0, _len = items.length; _i < _len; _i++) {
    item = items[_i];
    console.log(item);
  }

  for (i = _j = 5; _j >= 0; i = --_j) {
    alert(i);
  }

  for (_k = 0, _len1 = items.length; _k < _len1; _k++) {
    item = items[_k];
    if (item !== 'beer2') {
      console.log(item);
    }
  }

  drinkbeer = function() {
    var beer;
    beer = items.pop;
    return console.log(beer);
  };

  hello = function(name) {
    return console.log("Hello " + name);
  };

  fridge = {
    beer: items,
    chips: ["potato", "bbq", "human skin"],
    consume: function(item) {
      return item.pop();
    },
    drinkBeer: function() {
      return this.beer.pop();
    }
  };

  $(document).ready(function() {
    console.log('hello world, document is ready');
    $('div').on('click', function() {
      return console.log('there was a click');
    });
    return $('p').click(function() {
      return console.log('someone clicked a paragraph');
    });
  });

}).call(this);
