// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    console.log('document ready');
    console.log('live compiling');
    $(window).mousemove(function(event) {
      return console.log(event.pageX, event.pageY);
    });
    return $('p').on('click', function() {
      $(this).css('font-style', 'italic');
      return $('img').fadeToggle();
    });
  });

}).call(this);
